# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

script: .travis/build.sh "$TRAVIS_COMMIT_RANGE" "$PROJECT"

language: node_js
node_js:
  - "lts/*"

matrix:
  include:
    - os: linux
      dist: trusty
    - env: PROJECT=front-end/
