version: "3.8"

networks:
    test:
      name: test

services:
  postgres:
    image: nicholasadamou/postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=nicholas
      - POSTGRES_PASSWORD=p@ssw0rd123
    ports:
      - 9998:5432
    networks:
      - test
